/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './../../../app/routes/__root'
import { Route as LayoutRouteImport } from './../../../app/routes/_layout'
import { Route as LayoutIndexRouteImport } from './../../../app/routes/_layout.index'
import { Route as ProductsProductsRouteImport } from './../../../app/routes/products/products'
import { Route as ProductsProductsLayoutRouteImport } from './../../../app/routes/products/_products-layout'
import { Route as AuthRegistrationLayoutRouteImport } from './../../../app/routes/auth/_registration-layout'
import { Route as AuthAuthLayoutRouteImport } from './../../../app/routes/auth/_auth-layout'
import { Route as AuthAuthLayoutSigninRouteImport } from './../../../app/routes/auth/_auth-layout.signin'
import { Route as AuthAuthLayoutRegisterRouteImport } from './../../../app/routes/auth/_auth-layout.register'

const ProductsRouteImport = createFileRoute('/products')()
const AuthRouteImport = createFileRoute('/auth')()

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ProductsProductsRoute = ProductsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProductsLayoutRoute = ProductsProductsLayoutRouteImport.update({
  id: '/_products-layout',
  getParentRoute: () => ProductsRoute,
} as any)
const AuthRegistrationLayoutRoute = AuthRegistrationLayoutRouteImport.update({
  id: '/_registration-layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthLayoutRoute = AuthAuthLayoutRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthLayoutSigninRoute = AuthAuthLayoutSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const AuthAuthLayoutRegisterRoute = AuthAuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRegistrationLayoutRoute
  '/products': typeof ProductsProductsLayoutRoute
  '/products/products': typeof ProductsProductsRoute
  '/': typeof LayoutIndexRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/auth/signin': typeof AuthAuthLayoutSigninRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRegistrationLayoutRoute
  '/products': typeof ProductsProductsLayoutRoute
  '/products/products': typeof ProductsProductsRoute
  '/': typeof LayoutIndexRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/auth/signin': typeof AuthAuthLayoutSigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_auth-layout': typeof AuthAuthLayoutRouteWithChildren
  '/auth/_registration-layout': typeof AuthRegistrationLayoutRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/_products-layout': typeof ProductsProductsLayoutRoute
  '/products/products': typeof ProductsProductsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/auth/_auth-layout/register': typeof AuthAuthLayoutRegisterRoute
  '/auth/_auth-layout/signin': typeof AuthAuthLayoutSigninRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/products'
    | '/products/products'
    | '/'
    | '/auth/register'
    | '/auth/signin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/products'
    | '/products/products'
    | '/'
    | '/auth/register'
    | '/auth/signin'
  id:
    | '__root__'
    | '/_layout'
    | '/auth'
    | '/auth/_auth-layout'
    | '/auth/_registration-layout'
    | '/products'
    | '/products/_products-layout'
    | '/products/products'
    | '/_layout/'
    | '/auth/_auth-layout/register'
    | '/auth/_auth-layout/signin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/products/products': {
      id: '/products/products'
      path: '/products'
      fullPath: '/products/products'
      preLoaderRoute: typeof ProductsProductsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/_products-layout': {
      id: '/products/_products-layout'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsProductsLayoutRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/auth/_registration-layout': {
      id: '/auth/_registration-layout'
      path: ''
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRegistrationLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/_auth-layout': {
      id: '/auth/_auth-layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/_auth-layout/signin': {
      id: '/auth/_auth-layout/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthAuthLayoutSigninRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/auth/_auth-layout/register': {
      id: '/auth/_auth-layout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthLayoutRegisterRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutRegisterRoute: typeof AuthAuthLayoutRegisterRoute
  AuthAuthLayoutSigninRoute: typeof AuthAuthLayoutSigninRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutRegisterRoute: AuthAuthLayoutRegisterRoute,
  AuthAuthLayoutSigninRoute: AuthAuthLayoutSigninRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
  AuthRegistrationLayoutRoute: typeof AuthRegistrationLayoutRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
  AuthRegistrationLayoutRoute: AuthRegistrationLayoutRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProductsRouteChildren {
  ProductsProductsLayoutRoute: typeof ProductsProductsLayoutRoute
  ProductsProductsRoute: typeof ProductsProductsRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductsLayoutRoute: ProductsProductsLayoutRoute,
  ProductsProductsRoute: ProductsProductsRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
