/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './../../../app/routes/__root'
import { Route as LayoutRouteImport } from './../../../app/routes/_layout'
import { Route as ChatIndexRouteImport } from './../../../app/routes/chat/index'
import { Route as LayoutIndexRouteImport } from './../../../app/routes/_layout.index'
import { Route as ChatProductsRouteImport } from './../../../app/routes/chat/products'
import { Route as ChatChatLayoutRouteImport } from './../../../app/routes/chat/_chat-layout'
import { Route as AuthRegistrationLayoutRouteImport } from './../../../app/routes/auth/_registration-layout'
import { Route as AuthAuthLayoutRouteImport } from './../../../app/routes/auth/_auth-layout'
import { Route as AuthAuthLayoutSigninRouteImport } from './../../../app/routes/auth/_auth-layout.signin'
import { Route as AuthAuthLayoutRegisterRouteImport } from './../../../app/routes/auth/_auth-layout.register'

const ChatRouteImport = createFileRoute('/chat')()
const AuthRouteImport = createFileRoute('/auth')()

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ChatProductsRoute = ChatProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ChatRoute,
} as any)
const ChatChatLayoutRoute = ChatChatLayoutRouteImport.update({
  id: '/_chat-layout',
  getParentRoute: () => ChatRoute,
} as any)
const AuthRegistrationLayoutRoute = AuthRegistrationLayoutRouteImport.update({
  id: '/_registration-layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthLayoutRoute = AuthAuthLayoutRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthLayoutSigninRoute = AuthAuthLayoutSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const AuthAuthLayoutRegisterRoute = AuthAuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRegistrationLayoutRoute
  '/chat': typeof ChatChatLayoutRoute
  '/chat/products': typeof ChatProductsRoute
  '/': typeof LayoutIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/auth/signin': typeof AuthAuthLayoutSigninRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRegistrationLayoutRoute
  '/chat': typeof ChatIndexRoute
  '/chat/products': typeof ChatProductsRoute
  '/': typeof LayoutIndexRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/auth/signin': typeof AuthAuthLayoutSigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_auth-layout': typeof AuthAuthLayoutRouteWithChildren
  '/auth/_registration-layout': typeof AuthRegistrationLayoutRoute
  '/chat': typeof ChatRouteWithChildren
  '/chat/_chat-layout': typeof ChatChatLayoutRoute
  '/chat/products': typeof ChatProductsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/auth/_auth-layout/register': typeof AuthAuthLayoutRegisterRoute
  '/auth/_auth-layout/signin': typeof AuthAuthLayoutSigninRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/chat'
    | '/chat/products'
    | '/'
    | '/chat/'
    | '/auth/register'
    | '/auth/signin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/chat'
    | '/chat/products'
    | '/'
    | '/auth/register'
    | '/auth/signin'
  id:
    | '__root__'
    | '/_layout'
    | '/auth'
    | '/auth/_auth-layout'
    | '/auth/_registration-layout'
    | '/chat'
    | '/chat/_chat-layout'
    | '/chat/products'
    | '/_layout/'
    | '/chat/'
    | '/auth/_auth-layout/register'
    | '/auth/_auth-layout/signin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/chat/products': {
      id: '/chat/products'
      path: '/products'
      fullPath: '/chat/products'
      preLoaderRoute: typeof ChatProductsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/_chat-layout': {
      id: '/chat/_chat-layout'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatChatLayoutRouteImport
      parentRoute: typeof ChatRoute
    }
    '/auth/_registration-layout': {
      id: '/auth/_registration-layout'
      path: ''
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRegistrationLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/_auth-layout': {
      id: '/auth/_auth-layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/_auth-layout/signin': {
      id: '/auth/_auth-layout/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthAuthLayoutSigninRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/auth/_auth-layout/register': {
      id: '/auth/_auth-layout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthLayoutRegisterRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutRegisterRoute: typeof AuthAuthLayoutRegisterRoute
  AuthAuthLayoutSigninRoute: typeof AuthAuthLayoutSigninRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutRegisterRoute: AuthAuthLayoutRegisterRoute,
  AuthAuthLayoutSigninRoute: AuthAuthLayoutSigninRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
  AuthRegistrationLayoutRoute: typeof AuthRegistrationLayoutRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
  AuthRegistrationLayoutRoute: AuthRegistrationLayoutRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ChatRouteChildren {
  ChatChatLayoutRoute: typeof ChatChatLayoutRoute
  ChatProductsRoute: typeof ChatProductsRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatLayoutRoute: ChatChatLayoutRoute,
  ChatProductsRoute: ChatProductsRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
